---
title: Getting Started with AWS CDK
author: Armin Halim-Schneider
remote_theme: vsoch/mkdocs-jekyll

## Social
repo: https://github.com/arminhs/getting-started-with-aws-cdk
github_user: arminhs
github_repo: getting-started-with-aws-cdk
